version: "3.8"

services:
  frontend: # http://localhost:8080/
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=

  backend: # metrics: http://localhost:3000/metrics api: http://localhost:3000/
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "3000:3000"
    environment:
      - POSTGRES_URI=postgres://kanban_user:kanban_pass@postgres:5432/kanban
      - NODE_ENV=production
      - CORS_ORIGIN=http://localhost:8080,http://127.0.0.1:8080
      - PORT=3000
    depends_on:
      - postgres
    volumes:
      - .:/app
      - /app/node_modules

  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: kanban_user
      POSTGRES_PASSWORD: kanban_pass
      POSTGRES_DB: kanban
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

# docker compose up --build